### ISSUE TITLE
Upgrade from 5.0.x to 5.5.x

### ISSUE THREAD

**Issue by Robert-turbo** [m0wer/docker-taiga#6]
Hi,

first of all, I would like to thank you very much for a great work of maintaining this project! We are using it every day in our company :)

Second I would like to write about issue I had during upgrade from 5.0.15 to 5.5.0
After changing docker image tag in docker-compose and doing pull, down and up on docker-compose, postgres and taiga started to report errors:

```
ERROR:  column users_user.verified_email does not exist at character 556
postgres-taiga | STATEMENT:  SELECT "users_user"."id", "users_user"."password", "users_user"."last_login", "users_user"."is_superuser", "users_user"."uuid", "users_user"."username", "users_user"."email", "users_user"."is_active", "users_
user"."full_name", "users_user"."color", "users_user"."bio", "users_user"."photo", "users_user"."date_joined", "users_user"."accepted_terms", "users_user"."read_new_terms", "users_user"."lang", "users_user"."theme", "users_user"."timezon
e", "users_user"."colorize_tags", "users_user"."token", "users_user"."email_token", "users_user"."new_email", "users_user"."verified_email", "users_user"."is_system", "users_user"."max_private_projects", "users_user"."max_public_projects
", "users_user"."max_memberships_private_projects", "users_user"."max_memberships_public_projects" FROM "users_user" WHERE "users_user"."id" = 6
```

```
taiga       | ERROR:2020-10-10 16:45:43,270: Internal Server Error: /api/v1/projects
taiga       | Traceback (most recent call last):
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
taiga       |     return self.cursor.execute(sql, params)
taiga       | psycopg2.errors.UndefinedColumn: column users_user.verified_email does not exist
taiga       | LINE 1: ...rs_user"."email_token", "users_user"."new_email", "users_use...
taiga       |                                                              ^
taiga       |
taiga       |
taiga       | The above exception was the direct cause of the following exception:
taiga       |
taiga       | Traceback (most recent call last):
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
taiga       |     response = get_response(request)
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
taiga       |     response = self.process_exception_by_middleware(e, request)
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
taiga       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
taiga       |   File "/taiga.io/taiga-back-5.5.0/taiga/base/api/viewsets.py", line 106, in view
taiga       |     return self.dispatch(request, *args, **kwargs)
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
taiga       |     return view_func(*args, **kwargs)
taiga       |   File "/taiga.io/taiga-back-5.5.0/taiga/base/api/views.py", line 460, in dispatch
taiga       |     response = self.handle_exception(exc)
taiga       |   File "/taiga.io/taiga-back-5.5.0/taiga/base/api/views.py", line 449, in dispatch
taiga       |     self.initial(request, *args, **kwargs)
taiga       |   File "/taiga.io/taiga-back-5.5.0/taiga/base/api/views.py", line 379, in initial
taiga       |     self.perform_authentication(request)
taiga       |   File "/taiga.io/taiga-back-5.5.0/taiga/base/api/views.py", line 327, in perform_authentication
taiga       |     request.user
taiga       |   File "/taiga.io/taiga-back-5.5.0/taiga/base/api/request.py", line 264, in user
taiga       |     self._authenticate()
taiga       |   File "/taiga.io/taiga-back-5.5.0/taiga/base/api/request.py", line 430, in _authenticate
taiga       |     user_auth_tuple = authenticator.authenticate(self)
taiga       |   File "/taiga.io/taiga-back-5.5.0/taiga/auth/backends.py", line 89, in authenticate
taiga       |     max_age=max_age_auth_token)
taiga       |   File "/taiga.io/taiga-back-5.5.0/taiga/auth/tokens.py", line 54, in get_user_for_token
taiga       |     user = model_cls.objects.get(pk=data["user_%s_id" % (scope)])
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
taiga       |     return getattr(self.get_queryset(), name)(*args, **kwargs)
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
taiga       |     num = len(clone)
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
taiga       |     self._fetch_all()
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
taiga       |     self._result_cache = list(self._iterable_class(self))
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
taiga       |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
taiga       |     cursor.execute(sql, params)
taiga       |   File "/usr/local/lib/python3.6/site-packages/raven/contrib/django/client.py", line 127, in execute
taiga       |     return real_execute(self, sql, params)
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
taiga       |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
taiga       |     return executor(sql, params, many, context)
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
taiga       |     return self.cursor.execute(sql, params)
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
taiga       |     raise dj_exc_value.with_traceback(traceback) from exc_value
taiga       |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
taiga       |     return self.cursor.execute(sql, params)
taiga       | django.db.utils.ProgrammingError: column users_user.verified_email does not exist
taiga       | LINE 1: ...rs_user"."email_token", "users_user"."new_email", "users_use...
taiga       |                                                              ^

```

and I found solution :)
`docker exec -it taiga sh`
and then in container 

```
python manage.py migrate --noinput
python manage.py compilemessages
python manage.py collectstatic --noinput
```

It's from https://taigaio.github.io/taiga-doc/dist/upgrades.html

Maybe it should be executed during upgrade?

**Comment by m0wer** [comment]
I'm happy to hear that its useful for you :-)

About the migration problem: the instrucions that you quote appear under the "contrib plugins" section, did the problem occur in an instance with contrib plugins installed?

Do you think the migration commands should be added to [entrypoint.sh ](https://github.com/m0wer/docker-taiga/blob/master/entrypoint.sh) and be run on every start?

**Comment by Robert-turbo** [comment]
Hi,

it's under `DEFAULT UPGRADE PROCESS` and it's states

`If you have some contrib plugins installed you should to upgrade them before the next step.`

So, if you don't have this plugin, you don't have to upgrade it 🙂

I think that those migration commands should be run on every start.
Thanks

**Comment by m0wer** [comment]
Ok @Robert-turbo. Could you open a PR for it?
